### ISSUE TITLE
Fatal error when editing a snippet setup

### ISSUE THREAD

**Issue by csoutham** [adamfairholm/PyroSnippets#19]
This is in 2.1 dev branch of Pro using the latest 2.2.2 of Snippets:
Fatal error: Call to undefined function js() in /pyrocms/httpdocs/addons/shared_addons/modules/snippets/controllers/admin_setup.php on line 193

All other parts of Snippets seems fine :)

**Comment by adamfairholm** [comment]
Thanks Chris. This needs to be updated for the latest version which switches up all of the js template calls. I'll take a look.

**Comment by csoutham** [comment]
Hi Adam, no worries. I think I've fixed it locally by swapping out 193 and replacing with:
Asset::js('module::new_snippet.js');

**Comment by jayf** [comment]
This is still an issue in the current version -- please reopen. The fix got rolled back in d282da75852dd835189cf84d49c8afe7b3d5d1be -- and so this is breaking in PyroCMS 2.1.3. 

Using the "older" code from 61de0d7 fixes the issue.
